name: Build docker images
on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string
      docker_image_tag:
        default: latest
        required: false
        type: string
    secrets:
      docker_auth_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: docker/login-action@v2.1.0
        with:
          username: tareksamni
          password: ${{ secrets.docker_auth_token }}
      - uses: docker/setup-buildx-action@v2.5.0
      - uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ./${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
          target: ${{ inputs.image_target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
